config/routes.rb
Stepbystep::Application.routes.draw do

  resources :howtos do
    resources :steps
  end

   root 'howtos#index'

end

app/models/howto.rb
class Howto < ActiveRecord::Base
  has_many :steps

  accepts_nested_attributes_for :steps
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :howto
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/howtos_controller.rb
class HowtosController < ApplicationController


  # GET /howtos
  # GET /howtos.json
  def index
    @howtos = Howto.all
  end

  # GET /howtos/1
  # GET /howtos/1.json
  def show
    @howto = Howto.find(params[:id])
  end

  # GET /howtos/new
  def new
    @howto = Howto.new
  end

  # GET /howtos/1/edit
  def edit
    @howto = Howto.find(params[:id])
  end

  # POST /howtos
  # POST /howtos.json
  def create
    @howto = Howto.new(howto_params)

    respond_to do |format|
      if @howto.save
        format.html { redirect_to @howto, notice: 'Howto was successfully created.' }
        format.json { render action: 'show', status: :created, location: @howto }
      else
        format.html { render action: 'new' }
        format.json { render json: @howto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /howtos/1
  # PATCH/PUT /howtos/1.json
  def update
    @howto = Howto.find(params[:id])
    respond_to do |format|
      if @howto.update(howto_params)
        format.html { redirect_to @howto, notice: 'Howto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @howto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /howtos/1
  # DELETE /howtos/1.json
  def destroy
    @howto = Howto.find(params[:id])
    @howto.destroy
    respond_to do |format|
      format.html { redirect_to howtos_url }
      format.json { head :no_content }
    end
  end

  private

  def howto_params
    params.require(:howto).permit(:name, :description, steps_attributes: [ :name, :description])
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_filter :load_howto

  # GET /steps
  # GET /steps.json
  def index
    @steps = @howto.steps.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @steps }
    end
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @step = @howto.steps.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/new
  def new
    @step = @howto.steps.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/1/edit
  def edit
    @step = @howto.steps.find(params[:id])
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = @howto.steps.find(params[:step])

    respond_to do |format|
      if @step.save
        format.html { redirect_to @step, notice: 'Step was successfully created.' }
        format.json { render action: 'show', status: :created, location: @step }
      else
        format.html { render action: 'new' }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    @step = @howto.steps.find(params[:id])
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to [@howto, @step], notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step = @howto.steps.find(params[:id])
    @step.destroy
    respond_to do |format|
      format.html { redirect_to howto_steps_path(@howto) }
      format.json { head :no_content }
    end
  end

  private

  def load_howto
    @howto = Howto.find(params[:howto_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/howtos_helper.rb
module HowtosHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/howtos/_form.html.erb
<%= form_for(@howto) do |f| %>
<% if @howto.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@howto.errors.count, "error") %> prohibited this howto from being saved:</h2>

  <ul>
    <% @howto.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</div>
<strong>Task:</strong>
<%= f.fields_for :step do |step_form| %>
<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>
<% end %>

app/views/howtos/edit.html.erb
<h1>Editing howto</h1>

<%= render 'form' %>

<%= link_to 'Show', @howto %> |
<%= link_to 'Back', howtos_path %>

app/views/howtos/index.html.erb
<h1>Listing howtos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Task</th>
    </tr>
  </thead>

  <tbody>
    <% @howtos.each do |howto| %>
    <tr>
      <td><%= howto.id %></td>
      <td><%= howto.name %></td>
      <td><%= howto.description %></td>
      <td><%= howto.steps.name %></td>
      <td><%= link_to 'Show', howto %></td>
      <td><%= link_to 'Edit', edit_howto_path(howto) %></td>
      <td><%= link_to 'Destroy', howto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Howto', new_howto_path %>

app/views/howtos/new.html.erb
<h1>New howto</h1>

<%= render 'form' %>

<%= link_to 'Back', howtos_path %>

app/views/howtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @howto.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @howto.description %>
</p>

<%= link_to 'Edit', edit_howto_path(@howto) %> |
<%= link_to 'Back', howtos_path %>
<%= link_to 'add a new step', new_howto_step_path(@howto) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stepbystep</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for [@howto, @step] do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', howto_step_path(@howto, @step) %> |
<%= link_to 'Back', howto_steps_path(@howto) %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>HowTo</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.name %></td>
        <td><%= step.description %></td>
        <td><%= step.howto_id %>
        <td><%= link_to 'Show', howto_step_path(@howto, step) %></td>
        <td><%= link_to 'Edit', edit_howto_step_path(@howto, step) %></td>
        <td><%= link_to 'Destroy', [@howto, step], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step', new_howto_step_path(@howto) %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', howto_steps_path(@howto) %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @step.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @step.description %>
</p>

<p>
  <strong>Task:</strong>
  <%= @step.howto_id %>
</p>

<%= link_to 'Edit', edit_howto_step_path(@howto, @step) %> |
<%= link_to 'Back', howto_steps_path(@howto) %>